### ISSUE TITLE
particle update - should also work OTA

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/particle-cli#107]
if you specify a device name / id, it could send the system updates over the air?

**Comment by m-mcgowan** [comment]
Nice idea.  I imagine this triggers the auto-updater to start the update process and the appropriate binaries if the device is out of date. Managing the update from the cloud would be simpler in the long run since the cloud sees the current installed state of the device. 

Have to be very careful we don't inadvertently downgrade the modules on a device until that is supported in the auto-updater since that must be done in reverse order.

**Comment by brycekahle** [comment]
If we are updating system parts, can't we do part1 and then part2?

**Comment by m-mcgowan** [comment]
Yep, when updating that is the correct order, but when downgrading it should be in the reverse order, so that dependencies are always met. (part1 is a dependency of part2.)
