### ISSUE TITLE
Feature Request - particle backup

### ISSUE THREAD

**Issue by harrisonhjones** [particle-iot/particle-cli#297]
Following up on a request from @technobly I'd like to implement a `particle backup` command which would backup different sections of firmware to memory. I'd like to use this issue to outline the feature set for the feature. 

Syntax: `particle backup location filename`

**location parameter**
The area of firmware to backup. Can be one of the following:

- `all` - The entire memory space
- `system1` - The system part 1 area of the firmware
- `system2` - The system part 2 area of the firmware
- `system3` - The system part 3 area of the firmware
- `user` - The user area of the firmware
- `dct` - The dct area of the firmware
- `factory` - The factory area of the firmware
- `cloudKey` - The server key area of firmware
- `deviceKey` - The device key area of firmware

**filename parameter**
Allows the user to customize the output filename. The file extension is not customizable and inferred from the location. 

**Next Steps**

We already have a lot of the information we need in the [specifications](https://github.com/spark/particle-cli/blob/master/lib/deviceSpecs/specifications.js) file. What I need help with is determining each `location`'s "size" and then the address of `all` & `dtc`. I can't find these anywhere. I assume the format for all of these is `.bin` (except for the keys)

**Comment by m-mcgowan** [comment]
I can only click 👍  up once, but want a 💯 of them!

For completeness, how about we add these to the list too:

- `bootloader`
- `eeprom`
- `serverAddress` (the address block that is used to determine how to connect to the cloud.)
- `server` (saves `serverAddress` and `serverKey` at once.)

Let's also add the reverse: `restore`. This would be more limited since it's not possible to write to all memory regions. (e.g. `all` is unlikely to be supported, and similarly for `bootloader` and `dct`.)

From the security standpoint, this is equivalent to running a DFU command, so we are not providing any new functionality, merely a sweeter syntax. 

The key format is DER, however it we are going to be technically accurate then we can't call the file `.der` because we would have to decode the data to find out the exact length of the key, rather than using the entire memory region. so I suggest we keep it simple and call it `.bin` as well. Then the user can specify the full filename (with extension), which is typically what the user expects when using a CLI tool that writes a file. 

The CLI can determine the platform of the device from the USB info (and from the platform, the memory layout). Although for completeness and flexibility in cases where that's not possible, we can have a `--platform` flag (which has a default value of `auto`). 

That's my brain dump of thoughts, I'll add more if I think of them.
