### ISSUE TITLE
Particle CLI Installer (extra exe's for Windows needed)

### ISSUE THREAD

**Issue by technobly** [particle-iot/particle-cli#308]
Please see this issue reported in the Firmware repo:
https://github.com/spark/firmware/issues/1198

It's also worth noting that there is no public record of when the CLI installer is updated, and what the current version is.  This is also the reason I'm adding this issue to the wrong repo (Particle CLI) instead of Particle CLI Installer.

**Comment by monkbroc** [comment]
Let's discuss in a video chat but I think local compilation is out of scope for the CLI and installing the local compilation toolchain is out of scope for the CLI installer at this point. My suggestion would be to test drive the local compilation with buildpacks for the RPi project then roll out new CLI commands that invoke the correct Docker buildpack for the selected platform.

**Comment by m-mcgowan** [comment]
Just wanted to add my review that I'm also a bit puzzled about local compile dependencies being related to the CLI installer, since the CLI itself doesn't offer local compile at present (and when it does, it will be via buildpacks.)

@technobly - since the original issue in FW has been closed, are you happy closing this one too?
