### ISSUE TITLE
Only upload valid files

### ISSUE THREAD

**Issue by kennethlimcp** [particle-iot/particle-cli#324]
```
Compiling code for photon
Targeting version: 0.6.1-rc.2

Including:
    ColorSensor.ino
    ../../library.properties
    ../../src/README.md
    ../../src/SparkFun_APDS9960.cpp
    ../../src/Arduino.h
    ../../src/SparkFun_APDS9960.h
```

I'm sure the compile service has some defense against other file extension but we can minimize the surface attack vector by only uploading appropriate files. This also reduces the time taken to upload the source files :)

**Comment by kennethlimcp** [comment]
That's a good question. It simply came from upstream: https://github.com/sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library/tree/master/src

**Comment by m-mcgowan** [comment]
I think a first pass at this is to put a 2MB size filter on the files to send to the compile service, just in case someone accidentally includes something not needed, and also have a default list of files to exclude.

This is more a function for particle-api-js than the CLI, but since the CLI needs to interface to it, and possibly provide command-line options like `--max-size` and `--exclude-files`, then we'll keep this issue open here.
