### ISSUE TITLE
Issue flashing over USB

### ISSUE THREAD

**Issue by gibsongibbz** [particle-iot/particle-cli#402]
operating system :  ubuntu 17.0
CLI used  :  https://github.com/particle-iot/particle-cli.git
Flashing in Listening mode 

Error writing firmware...Error: Error: Permission denied, cannot open /dev/ttyACM0
Error: Error: Permission denied, cannot open /dev/ttyACM0
    at Error (native)

**Comment by kennethlimcp** [comment]
Try with sudo

ken,
sent on mobile

On 15 Feb 2018 4:57 pm, "gibsongibbz" <notifications@github.com> wrote:

operating system : ubuntu 17.0
CLI used : https://github.com/particle-iot/particle-cli.git
Flashing in Listening mode

Error writing firmware...Error: Error: Permission denied, cannot open
/dev/ttyACM0
Error: Error: Permission denied, cannot open /dev/ttyACM0
at Error (native)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/particle-iot/particle-cli/issues/402>, or mute the
thread

**Comment by gibsongibbz** [comment]
finding the Same error with Sudo

**Comment by kennethlimcp** [comment]
Try this: https://github.com/particle-iot/particle-cli/blob/master/assets/50-particle.rules
