### ISSUE TITLE
add a particle flash --no-touch option

### ISSUE THREAD

**Issue by marshallbrown123** [particle-iot/particle-cli#417]
It seems like a small step to add a particle flash --no-touch option to load firmware into a USB connected device via the particle CLI

There are several options available to put the device into either listening mode or DFU mode without touching doing the reset/mode button dance. 

for DFU mode (as this is what I use) 
1. set the serial port to 14400, 

2. device switches to DFU mode. 

3. disconnect the serial port. 

4. particle flash --usb somefilename.bin

5. done. 

if the particle CLI had the option to set the baudrate it's pretty well done, with the above steps. 

the command would look like this

particle flash --no-touch somefilename.bin

**Comment by technobly** [comment]
Nice feature idea!

How about extending the api instead of renaming something like `--usb` to `--no-touch` because we also have `--serial`, so maybe something like this:

```
particle flash --usb firmware.bin --dfu-mode
particle flash --serial firmware.bin --listening-mode
```

You could also use the --no-touch as a universal way, but I would also like to have the ability to explicitly enter a mode.
```
particle flash --usb firmware.bin --no-touch
particle flash --serial firmware.bin --no-touch
```

This could also be applied to many other CLI commands that require these modes.  

This should also work with `--port` for when you have multiple devices attached
```
particle flash --usb firmware.bin --dfu-mode --port /dev/cu.usbmodem141421
particle flash --serial firmware.bin --listening-mode --port /dev/cu.usbmodem141421
```
**Note:** currently `--serial` doesn't not support the use of `--port` see #406
