### ISSUE TITLE
particle keys server `--port` not working in v1.29.0

### ISSUE THREAD

**Issue by technobly** [particle-iot/particle-cli#419]
I'm guessing `--port` is getting confused with the serial port for the host machine, instead of the TCP/UDP port for the server address.

`--port 5684` for example does not update the port in the server address on the device.

Full example:
```
particle keys server ec.pub.der --host 192.168.1.1 --port 5684 --protocol udp
```

**Comment by monkbroc** [comment]
There was a strange caching of the modified key in this command. If you ran the command multiple times and changed the port it wouldn't re-generate the key with the new port.

Fixed in 1.31.0. Try it with `npm install -g https://github.com/particle-iot/particle-cli/releases/download/v1.31.0-rc.2/particle-cli-1.31.0-rc.2.tgz`
